#PM dec 2025

#This file will contain any and all constant values for the discord bot.

#import the timetrials constants
import os
import sys
parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(parent_dir)

from time_trials.constants import *

#Currently supported TT players
TIME_TRIAL_PLAYERS=["Pat", "Kevin", "Demitri", "John", "Mike", "Chris"]

#TimeTrialTracks
TIME_TRIAL_TRACKS=["Luigi Circuit",
  "Moo Moo Meadows",
  "Mushroom Gorge",
  "Toad's Factory",
  "Mario Circuit",
  "Coconut Mall",
  "DK's Snowboard Cross",
  "Wario's Gold Mine",
  "Daisy Circuit",
  "Koopa Cape",
  "Maple Treeway",
  "Grumble Volcano",
  "Dry Dry Ruins",
  "Moonview Highway",
  "Bowser's Castle",
  "Rainbow Road",
  "GCN Peach Beach",
  "DS Yoshi Falls",
  "SNES Ghost Valley 2",
  "N64 Mario Raceway",
  "N64 Sherbet Land",
  "GBA Shy Guy Beach",
  "DS Delfino Square",
  "GCN Waluigi Stadium",
  "DS Desert Hills",
  "GBA Bowser Castle 3",
  "N64 DK's Jungle Parkway",
  "GCN Mario Circuit",
  "SNES Mario Circuit 3",
  "DS Peach Gardens",
  "GCN DK Mountain",
  "N64 Bowser's Castle"]

TRACK_NICKNAME_LIST = {"Luigi":"Luigi Circuit",
    "LC":"Luigi Circuit",
    "moo moo": "Moo Moo Meadows",
    "Moo Moo": "Moo Moo Meadows",
    "MMM": "Moo Moo Meadows",
    "Gorge":"Mushroom Gorge",
    "gorge":"Mushroom Gorge",
    "MG":"Mushroom Gorge",
    "toads":"Toad's Factory",
    "Toads":"Toad's Factory",
    "TF":"Toad's Factory",
    "toads factory": "Toad's Factory",
    "mario circuit": "Mario Circuit",
    "MC": "Mario Circuit",
    "coconut mall":"Coconut Mall",
    "coconut":"Coconut Mall",
    "CM":"Coconut Mall",
    "summit":"DK Summit",
    "Summit":"DK Summit",
    "DKS":"DK Summit",
    "gold mine":"Wario's Gold Mine",
    "Gold Mine":"Wario's Gold Mine",
    "WGM":"Wario's Gold Mine",
    "DC" : "Daisy Circuit",
    "koopa": "Koopa Cape",
    "Koopa": "Koopa Cape",
    "KC": "Koopa Cape",
    "maple":"Maple Treeway",
    "Maple":"Maple Treeway",
    "MT":"Maple Treeway",
    "grumble":"Grumble Volcano",
    "Grumble":"Grumble Volcano",
    "GV":"Grumble Volcano",
    "Dry Dry":"Dry Dry Ruins",
    "dry dry":"Dry Dry Ruins",
    "DDR":"Dry Dry Ruins",
    "Moonview":"Moonview Highway",
    "moonview":"Moonview Highway",
    "MH":"Moonview Highway",
    "BC Wii":"Bowser's Castle",
    "bc wii":"Bowser's Castle",
    "BC wii":"Bowser's Castle",
    "BCWII":"Bowser's Castle",
    "BCWii":"Bowser's Castle",
    "BCW":"Bowser's Castle",
    "rainbow road":"Rainbow Road",
    "rainbow":"Rainbow Road",
    "Rainbow":"Rainbow Road",
    "RR":"Rainbow Road",
    "Peach Beach":"GCN Peach Beach",
    "peach beach":"GCN Peach Beach",
    "PB":"GCN Peach Beach",
    "yoshi falls":"DS Yoshi Falls",
    "Yoshi Falls":"DS Yoshi Falls",
    "YF":"DS Yoshi Falls",
    "Ghost Valley":"SNES Ghost Valley 2",
    "ghost valley":"SNES Ghost Valley 2",
    "GV2":"SNES Ghost Valley 2",
    "mario raceway":"N64 Mario Raceway",
    "raceway": "N64 Mario Raceway",
    "Raceway": "N64 Mario Raceway",
    "MR":"N64 Mario Raceway",
    "Sherbet Land":"N64 Sherbet Land",
    "sherbet land":"N64 Sherbet Land",
    "SL":"N64 Sherbet Land",
    "Shy Guy Beach":"GBA Shy Guy Beach",
    "shy guy beach":"GBA Shy Guy Beach",
    "Shy Guy":"GBA Shy Guy Beach",
    "shy guy":"GBA Shy Guy Beach",
    "SGB":"GBA Shy Guy Beach",
    "Delfino Square":"DS Delfino Square",
    "delfino square":"DS Delfino Square",
    "Delfino":"DS Delfino Square",
    "delfino":"DS Delfino Square",
    "DS":"DS Delfino Square",
    "Waluigi Stadium":"GCN Waluigi Stadium",
    "waluigi stadium":"GCN Waluigi Stadium",
    "WS":"GCN Waluigi Stadium",
    "Waluigi":"GCN Waluigi Stadium",
    "waluigi":"GCN Waluigi Stadium",
    "Desert Hills":"DS Desert Hills",
    "desert hills":"DS Desert Hills",
    "DH":"DS Desert Hills",
    "GBA 3":"GBA Bowser's Castle 3",
    "gba 3":"GBA Bowser's Castle 3",
    "BC3":"GBA Bowser's Castle 3",
    "bc3":"GBA Bowser's Castle 3",
    "Parkway":"N64 DK's Jungle Parkway",
    "parkway":"N64 DK's Jungle Parkway",
    "DKJP":"N64 DK's Jungle Parkway",
    "GCN mario circuit":"GCN Mario Circuit",
    "GCN mario":"GCN Mario Circuit",
    "gcn mario":"GCN Mario Circuit",
    "GCN Mario":"GCN Mario Circuit",
    "GCNMC":"GCN Mario Circuit",
    "SNES 3":"SNES Mario Circuit 3",
    "SNES3":"SNES Mario Circuit 3",
    "MC3":"SNES Mario Circuit 3",
    "snes 3":"SNES Mario Circuit 3",
    "Peach Gardens":"DS Peach Gardens",
    "peach gardens":"DS Peach Gardens",
    "PG":"DS Peach Gardens",
    "DK Mountain": "GCN DK Mountain",
    "DKM": "GCN DK Mountain",
    "dk mountain": "GCN DK Mountain",
    "mountain": "GCN DK Mountain",
    "Mountain": "GCN DK Mountain",
    "BC64":"N64 Bowser's Castle",
    "BCR":"N64 Bowser's Castle",
    "bc64":"N64 Bowser's Castle",
    "bc 64":"N64 Bowser's Castle",
    "N64BC":"N64 Bowser's Castle",
    "n64bc":"N64 Bowser's Castle",
    "LL" : "Lava Lake",
    "SS": "Stargaze Summit",
    "ES" : "Envenom Snowstorm",
    "DBG": "Dragon Burial Grounds",
    "BJCC": "Bowser Jr.'s Crafty Castle",
    "N64RR" : "N64 Royal Raceway",
    "AF": "DS Airstrip Fortress",
    "DKR": "DK Ruins",
    "BCDS" : "DS Bowser's Castle",
    "WC" : "Wolf Castlegrounds"}
TIME_TRIAL_SHORTCUT_TRACKS = [
     "Mushroom Gorge",
     "Coconut Mall",
     "Wario's Gold Mine",
     "Grumble Volcano",
     "Bowser's Castle",
     "GBA Bowser Castle 3"
]
